### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by HadesDa** [zZan54/BananaDropFarm#12]
i installed requirements using pip install -r requirements.txt but not work
![image](https://github.com/user-attachments/assets/44b0c35d-1c32-4f20-a96d-8f69593906c3)
same issue as with console build
![image](https://github.com/user-attachments/assets/7bbb06ab-bc65-4989-8a90-097c1448387c)

here is my output compiling
//
Requirement already satisfied: pymem==1.13.1 in c:\users\hades\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 1)) (1.13.1)
Collecting PyYAML==5.4.1 (from -r requirements.txt (line 2))
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib3\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib3\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib3\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Users\hades\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\hades\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hades\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hades\AppData\Local\Temp\pip-build-env-fs77mxi1\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hades\AppData\Local\Temp\pip-build-env-fs77mxi1\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\hades\AppData\Local\Temp\pip-build-env-fs77mxi1\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "C:\Users\hades\AppData\Local\Temp\pip-build-env-fs77mxi1\overlay\Lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hades\AppData\Local\Temp\pip-build-env-fs77mxi1\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\hades\AppData\Local\Temp\pip-build-env-fs77mxi1\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\hades\AppData\Local\Temp\pip-build-env-fs77mxi1\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "C:\Users\hades\AppData\Local\Temp\pip-build-env-fs77mxi1\overlay\Lib\site-packages\setuptools\dist.py", line 945, in run_command
          super().run_command(command)
        File "C:\Users\hades\AppData\Local\Temp\pip-build-env-fs77mxi1\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 989, in run_command
          cmd_obj.run()
        File "C:\Users\hades\AppData\Local\Temp\pip-build-env-fs77mxi1\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 310, in run
          self.find_sources()
        File "C:\Users\hades\AppData\Local\Temp\pip-build-env-fs77mxi1\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 318, in find_sources
          mm.run()
        File "C:\Users\hades\AppData\Local\Temp\pip-build-env-fs77mxi1\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 539, in run
          self.add_defaults()
        File "C:\Users\hades\AppData\Local\Temp\pip-build-env-fs77mxi1\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 577, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\hades\AppData\Local\Temp\pip-build-env-fs77mxi1\overlay\Lib\site-packages\setuptools\command\sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "C:\Users\hades\AppData\Local\Temp\pip-build-env-fs77mxi1\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 250, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\hades\AppData\Local\Temp\pip-build-env-fs77mxi1\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 335, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "C:\Users\hades\AppData\Local\Temp\pip-build-env-fs77mxi1\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
All requirements installed.
This script will turn BananaDropFarm into an executable.
The --noconsole option hides the console window when you run the executable.
If you set debug to true in menu.py, you will not be able to see the output if you use --noconsole.
Do you want to use the --noconsole option? (y/n)
n
253 INFO: PyInstaller: 6.9.0, contrib hooks: 2024.7
253 INFO: Python: 3.12.5
294 INFO: Platform: Windows-10-10.0.19045-SP0
294 INFO: Python environment: C:\Users\hades\AppData\Local\Programs\Python\Python312
296 INFO: wrote C:\Users\hades\Desktop\BananaDropFarm-1.6\BananaDropFarm.spec
306 INFO: Module search paths (PYTHONPATH):
['C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\pyinstaller.exe',
 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\python312.zip',
 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\DLLs',
 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib',
 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312',
 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages',
 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\setuptools\\_vendor',
 'C:\\Users\\hades\\Desktop\\BananaDropFarm-1.6']
551 INFO: checking Analysis
552 INFO: Building Analysis because Analysis-00.toc is non existent
552 INFO: Running Analysis Analysis-00.toc
566 INFO: Target bytecode optimization level: 0
566 INFO: Initializing module dependency graph...
568 INFO: Caching module graph hooks...
579 INFO: Analyzing base_library.zip ...
1777 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
1852 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
3413 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
4568 INFO: Caching module dependency graph...
4661 INFO: Looking for Python shared library...
4666 INFO: Using Python shared library: C:\Users\hades\AppData\Local\Programs\Python\Python312\python312.dll
4666 INFO: Analyzing C:\Users\hades\Desktop\BananaDropFarm-1.6\menu.py
4769 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
4868 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
5045 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
5213 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
6294 INFO: Loading module hook 'hook-psutil.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6365 INFO: Loading module hook 'hook-customtkinter.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6547 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
6604 INFO: Loading module hook 'hook-packaging.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
7148 INFO: Processing module hooks...
7235 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
8266 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
8292 INFO: Loading module hook 'hook-jaraco.text.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
8431 INFO: Loading module hook 'hook-importlib_resources.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
8823 INFO: Loading module hook 'hook-backports.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
8858 INFO: Loading module hook 'hook-platformdirs.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
8940 WARNING: Hidden import "pkg_resources._vendor.jaraco.functools" not found!
8940 WARNING: Hidden import "pkg_resources._vendor.jaraco.context" not found!
8942 WARNING: Hidden import "pkg_resources._vendor.jaraco.text" not found!
8943 WARNING: Hidden import "pkg_resources.extern" not found!
8978 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
8979 INFO: checking Tree
8979 INFO: Building Tree because Tree-00.toc is non existent
8980 INFO: Building Tree Tree-00.toc
9023 INFO: checking Tree
9023 INFO: Building Tree because Tree-01.toc is non existent
9024 INFO: Building Tree Tree-01.toc
9031 INFO: checking Tree
9031 INFO: Building Tree because Tree-02.toc is non existent
9031 INFO: Building Tree Tree-02.toc
9034 WARNING: Hidden import "importlib_resources.trees" not found!
9044 INFO: Performing binary vs. data reclassification (935 entries)
9203 INFO: Looking for ctypes DLLs
9239 WARNING: Ignoring AppKit.framework/AppKit imported from C:\Users\hades\AppData\Local\Programs\Python\Python312\Lib\site-packages\darkdetect\_mac_detect.py - only basenames are supported with ctypes imports!
9254 INFO: Analyzing run-time hooks ...
9256 INFO: Including run-time hook 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
9258 INFO: Including run-time hook 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
9261 INFO: Processing pre-find module path hook _pyi_rth_utils from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-_pyi_rth_utils.py'.
9263 INFO: Loading module hook 'hook-_pyi_rth_utils.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
9264 INFO: Including run-time hook 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
9267 INFO: Including run-time hook 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
9270 INFO: Including run-time hook 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
9296 INFO: Looking for dynamic libraries
9773 INFO: Extra DLL search directories (AddDllDirectory): []
9774 INFO: Extra DLL search directories (PATH): []
10050 INFO: Warnings written to C:\Users\hades\Desktop\BananaDropFarm-1.6\build\BananaDropFarm\warn-BananaDropFarm.txt
10086 INFO: Graph cross-reference written to C:\Users\hades\Desktop\BananaDropFarm-1.6\build\BananaDropFarm\xref-BananaDropFarm.html
10127 INFO: checking PYZ
10127 INFO: Building PYZ because PYZ-00.toc is non existent
10128 INFO: Building PYZ (ZlibArchive) C:\Users\hades\Desktop\BananaDropFarm-1.6\build\BananaDropFarm\PYZ-00.pyz
10695 INFO: Building PYZ (ZlibArchive) C:\Users\hades\Desktop\BananaDropFarm-1.6\build\BananaDropFarm\PYZ-00.pyz completed successfully.
10725 INFO: checking PKG
10725 INFO: Building PKG because PKG-00.toc is non existent
10726 INFO: Building PKG (CArchive) BananaDropFarm.pkg
13513 INFO: Building PKG (CArchive) BananaDropFarm.pkg completed successfully.
13531 INFO: Bootloader C:\Users\hades\AppData\Local\Programs\Python\Python312\Lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
13532 INFO: checking EXE
13532 INFO: Building EXE because EXE-00.toc is non existent
13533 INFO: Building EXE from EXE-00.toc
13533 INFO: Copying bootloader EXE to C:\Users\hades\Desktop\BananaDropFarm-1.6\dist\BananaDropFarm.exe
13571 INFO: Copying icon to EXE
13606 INFO: Copying 0 resources to EXE
13606 INFO: Embedding manifest in EXE
13640 INFO: Appending PKG archive to EXE
13654 INFO: Fixing EXE headers
13790 INFO: Building EXE from EXE-00.toc completed successfully.
PyInstaller build succeeded.
        1 file(s) moved.
Successfully moved the executable to the current directory.
Deleting the dist folder...
Deleting the build folder...
Deleting the BananaDropFarm.spec file...
Cleanup completed.
Press any key to continue . . .
//

**Comment by zZan54** [comment]
It looks like you're encountering an issue with the PyYAML dependency when building your project. This is a known problem with older versions of PyYAML. Here are two options to resolve this issue:
1. Download the Current Main Branch: The latest code in the main branch may already include updates that fix this issue. You can clone the current main branch directly from the repository instead of using the latest release. 
```sh
git clone https://github.com/zZan54/BananaDropFarm.git
cd BananaDropFarm
pip install -r requirements.txt
```
2. Update the PyYAML Version: Alternatively, you can manually update the PyYAML version in your requirements.txt file. Change the version from 5.4.1 to 6.0.1.

This should resolve the build error you're encountering. If you have any further issues, feel free to ask!

**Comment by HadesDa** [comment]
i tried both ways, not fixed.
also i deleted requirements from appdata and redownloaded but still not work

//
Requirement already satisfied: pymem==1.13.1 in c:\users\hades\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 1)) (1.13.1)
Requirement already satisfied: PyYAML==6.0.1 in c:\users\hades\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: psutil==5.9.8 in c:\users\hades\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 3)) (5.9.8)
Requirement already satisfied: customtkinter==5.2.2 in c:\users\hades\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 4)) (5.2.2)
Requirement already satisfied: pyinstaller in c:\users\hades\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 5)) (6.9.0)
Requirement already satisfied: darkdetect in c:\users\hades\appdata\local\programs\python\python312\lib\site-packages (from customtkinter==5.2.2->-r requirements.txt (line 4)) (0.8.0)
Requirement already satisfied: packaging in c:\users\hades\appdata\local\programs\python\python312\lib\site-packages (from customtkinter==5.2.2->-r requirements.txt (line 4)) (24.1)
Requirement already satisfied: setuptools>=42.0.0 in c:\users\hades\appdata\local\programs\python\python312\lib\site-packages (from pyinstaller->-r requirements.txt (line 5)) (72.1.0)
Requirement already satisfied: altgraph in c:\users\hades\appdata\local\programs\python\python312\lib\site-packages (from pyinstaller->-r requirements.txt (line 5)) (0.17.4)
Requirement already satisfied: pyinstaller-hooks-contrib>=2024.7 in c:\users\hades\appdata\local\programs\python\python312\lib\site-packages (from pyinstaller->-r requirements.txt (line 5)) (2024.7)
Requirement already satisfied: pefile>=2022.5.30 in c:\users\hades\appdata\local\programs\python\python312\lib\site-packages (from pyinstaller->-r requirements.txt (line 5)) (2023.2.7)
Requirement already satisfied: pywin32-ctypes>=0.2.1 in c:\users\hades\appdata\local\programs\python\python312\lib\site-packages (from pyinstaller->-r requirements.txt (line 5)) (0.2.2)
All requirements installed.
This script will turn BananaDropFarm into an executable.
The --noconsole option hides the console window when you run the executable.
If you set debug to true in menu.py, you will not be able to see the output if you use --noconsole.
Do you want to use the --noconsole option? (y/n)
y
261 INFO: PyInstaller: 6.9.0, contrib hooks: 2024.7
261 INFO: Python: 3.12.5
291 INFO: Platform: Windows-10-10.0.19045-SP0
291 INFO: Python environment: C:\Users\hades\AppData\Local\Programs\Python\Python312
293 INFO: wrote C:\Users\hades\Desktop\BananaDropFarm-main\BananaDropFarm.spec
297 INFO: Module search paths (PYTHONPATH):
['C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\pyinstaller.exe',
 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\python312.zip',
 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\DLLs',
 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib',
 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312',
 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages',
 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\setuptools\\_vendor',
 'C:\\Users\\hades\\Desktop\\BananaDropFarm-main']
522 INFO: checking Analysis
523 INFO: Building Analysis because Analysis-00.toc is non existent
524 INFO: Running Analysis Analysis-00.toc
525 INFO: Target bytecode optimization level: 0
525 INFO: Initializing module dependency graph...
527 INFO: Caching module graph hooks...
539 INFO: Analyzing base_library.zip ...
1591 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
1628 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
3381 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
4493 INFO: Caching module dependency graph...
4585 INFO: Looking for Python shared library...
4591 INFO: Using Python shared library: C:\Users\hades\AppData\Local\Programs\Python\Python312\python312.dll
4591 INFO: Analyzing C:\Users\hades\Desktop\BananaDropFarm-main\menu.py
4692 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
4791 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
4994 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
5130 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
6220 INFO: Loading module hook 'hook-psutil.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6288 INFO: Loading module hook 'hook-customtkinter.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6469 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
6524 INFO: Loading module hook 'hook-packaging.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
7063 INFO: Processing module hooks...
7176 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
8101 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
8127 INFO: Loading module hook 'hook-jaraco.text.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
8248 INFO: Loading module hook 'hook-importlib_resources.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
8635 INFO: Loading module hook 'hook-backports.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
8671 INFO: Loading module hook 'hook-platformdirs.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
8754 WARNING: Hidden import "pkg_resources._vendor.jaraco.functools" not found!
8755 WARNING: Hidden import "pkg_resources._vendor.jaraco.context" not found!
8756 WARNING: Hidden import "pkg_resources._vendor.jaraco.text" not found!
8757 WARNING: Hidden import "pkg_resources.extern" not found!
8794 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
8795 INFO: checking Tree
8796 INFO: Building Tree because Tree-00.toc is non existent
8796 INFO: Building Tree Tree-00.toc
8841 INFO: checking Tree
8841 INFO: Building Tree because Tree-01.toc is non existent
8842 INFO: Building Tree Tree-01.toc
8849 INFO: checking Tree
8849 INFO: Building Tree because Tree-02.toc is non existent
8849 INFO: Building Tree Tree-02.toc
8852 WARNING: Hidden import "importlib_resources.trees" not found!
8862 INFO: Performing binary vs. data reclassification (935 entries)
9022 INFO: Looking for ctypes DLLs
9059 WARNING: Ignoring AppKit.framework/AppKit imported from C:\Users\hades\AppData\Local\Programs\Python\Python312\Lib\site-packages\darkdetect\_mac_detect.py - only basenames are supported with ctypes imports!
9074 INFO: Analyzing run-time hooks ...
9076 INFO: Including run-time hook 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
9078 INFO: Including run-time hook 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
9081 INFO: Processing pre-find module path hook _pyi_rth_utils from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-_pyi_rth_utils.py'.
9083 INFO: Loading module hook 'hook-_pyi_rth_utils.py' from 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
9085 INFO: Including run-time hook 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
9088 INFO: Including run-time hook 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
9091 INFO: Including run-time hook 'C:\\Users\\hades\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
9117 INFO: Looking for dynamic libraries
9536 INFO: Extra DLL search directories (AddDllDirectory): []
9536 INFO: Extra DLL search directories (PATH): []
9820 INFO: Warnings written to C:\Users\hades\Desktop\BananaDropFarm-main\build\BananaDropFarm\warn-BananaDropFarm.txt
9857 INFO: Graph cross-reference written to C:\Users\hades\Desktop\BananaDropFarm-main\build\BananaDropFarm\xref-BananaDropFarm.html
9899 INFO: checking PYZ
9899 INFO: Building PYZ because PYZ-00.toc is non existent
9900 INFO: Building PYZ (ZlibArchive) C:\Users\hades\Desktop\BananaDropFarm-main\build\BananaDropFarm\PYZ-00.pyz
10464 INFO: Building PYZ (ZlibArchive) C:\Users\hades\Desktop\BananaDropFarm-main\build\BananaDropFarm\PYZ-00.pyz completed successfully.
10494 INFO: checking PKG
10494 INFO: Building PKG because PKG-00.toc is non existent
10495 INFO: Building PKG (CArchive) BananaDropFarm.pkg
13260 INFO: Building PKG (CArchive) BananaDropFarm.pkg completed successfully.
13745 INFO: Bootloader C:\Users\hades\AppData\Local\Programs\Python\Python312\Lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\runw.exe
13746 INFO: checking EXE
13746 INFO: Building EXE because EXE-00.toc is non existent
13746 INFO: Building EXE from EXE-00.toc
13747 INFO: Copying bootloader EXE to C:\Users\hades\Desktop\BananaDropFarm-main\dist\BananaDropFarm.exe
13783 INFO: Copying icon to EXE
13815 INFO: Copying 0 resources to EXE
13815 INFO: Embedding manifest in EXE
13847 INFO: Appending PKG archive to EXE
13862 INFO: Fixing EXE headers
14005 INFO: Building EXE from EXE-00.toc completed successfully.
PyInstaller build succeeded.
        1 file(s) moved.
Successfully moved the executable to the current directory.
Deleting the dist folder...
Deleting the build folder...
Deleting the BananaDropFarm.spec file...
Cleanup completed.
Press any key to continue . . .
//

**Comment by zZan54** [comment]
Try upgrading PyYAML directly using pip, run `pip install -U PyYAML` before running build.bat.

**Comment by HadesDa** [comment]
solved with 6.0.2 ty <3

**Comment by HZRDR** [comment]
I have similar problem but in line 14

Traceback (most recent call last):
  File "menu.py", line 14, in <module>
    from pystyle import Colorate, Colors, Center
ModuleNotFoundError: No module named 'pystyle'

PyYAML 6.0.2 is isntalled
